name: hcsub
description: "Community Resource Sharing Platform - Revolutionary Flutter App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Navigation
  go_router: ^14.2.7
  
  # HTTP & Networking
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  
  # Local Storage & Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  
  # UI & Design
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  
  # Utilities
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  
  # Location & Maps
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  
  # Image & Camera
  image_picker: ^1.1.2
  image_cropper: ^8.0.1
  
  # Animations
  lottie: ^3.1.2
  
  # Date & Time
  intl: ^0.19.0
  
  # Authentication & Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_messaging: ^14.9.4
  google_sign_in: ^6.2.1
  local_auth: ^2.1.8
  
  # Notifications
  flutter_local_notifications: ^17.2.2
  
  # Permissions
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1
  isar_generator: ^3.1.0+1
  
  # Linting
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/config/